AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-auth - Função Lambda para autenticação de clientes

Globals:
  Function:
    Timeout: 20
    MemorySize: 512
    Runtime: java17

Resources:
  MyAuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: auth.App::handleRequest
      Runtime: java17
      Architectures:
        - x86_64
      CodeUri: MyAuthFunction/
      Environment:
        Variables:
          SECRET_KEY: "your-secret-key"  # Adicione a chave secreta usada para JWT
          API_GATEWAY_BACKEND_URL: "https://api-gateway-backend-url.com"  # URL do backend principal
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        Authenticate:
          Type: Api
          Properties:
            Path: /authenticate
            Method: post

Outputs:
  MyAuthApi:
    Description: "API Gateway endpoint URL for MyAuthFunction"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/authenticate"
  MyAuthFunctionArn:
    Description: "MyAuth Lambda Function ARN"
    Value: !GetAtt MyAuthFunction.Arn
